Product Api Spec 정의
meshkorea/springbootcamp pull request #2
Opened 2022-12-06 08:31 UTC by twkim5235

### Description

- Product에 대한 API 스펙을 정의하였습니다.

### API List

- create Product: 상품 생성
- update Product: 상품 수정
- delete Product: 상품 제거
- list Products: 상품 목록 조회
- get Product: 개별 상품 조회

2022-12-07 00:33 UTC, appkr requested changes

2022-12-07 00:33 UTC, appkr commented on product/src/main/resources/swagger/api.yml
> +          $ref: '#/components/responses/NotFound'
리스트 요청에서 404가 나는 경우가 있을까요? 보통 검색 결과가 없으면 200 코드에 빈 모델을 응답하지 않나요?

2022-12-07 00:33 UTC, appkr commented on product/src/main/resources/swagger/api.yml
> -          $ref: '#/components/responses/Forbidden'
listProducts는 인증 없이도 사용할 수 있도록 설계하려는 의도라면, security 필드를 선언해 주세요. https://swagger.io/docs/specification/authentication/

2022-12-07 00:33 UTC, appkr commented on product/src/main/resources/swagger/api.yml
> +
Integer란 이름은 예약어일 가능성이 높습니다. IntegerId로 바꿔주세요.

2022-12-07 00:54 UTC, appkr reviewed
컨트롤러 테스트도 포함해주세요. 제가 슬랙에 공유했던 커밋 이력 링크와 다른 프로젝트 참고 바랍니다.

2022-12-08 01:08 UTC, twkim5235 commented on product/src/main/resources/swagger/api.yml
> +          $ref: '#/components/responses/NotFound'
넵 빈 객체를 응답하도록 변경하겠습니다.

2022-12-08 02:16 UTC, appkr requested changes

2022-12-08 02:16 UTC, appkr commented on product/src/main/resources/swagger/api.yml
> +            application/json:
커스텀 미디어 타입 적용 바랍니다.

2022-12-08 02:16 UTC, appkr commented on product/src/main/resources/swagger/api.yml
> +          $ref: '#/components/schemas/StringField'
https://meshkorea.slack.com/archives/C8MEULSNM/p1670372700812339?thread_ts=1670372089.069309&cid=C8MEULSNM

2022-12-09 06:12 UTC, closed without merging